### PR TITLE
remove w-tags

### PR DESCRIPTION
**Pull request by anagnosis**

### CODE REVIEW

**Comment by paregorios** [comment]
@HolgerEssler @anagnosis are there any issues or other discussion related to this pull request? What's the motivation?

**Comment by HolgerEssler** [comment]
This should solve Issues DCLP/dclpxsltbox/issues/178, DCLP/dclpxsltbox/issues/179 and DCLP/dclpxsltbox/issues/181. Explanation under DCLP/dclpxsltbox/issues/181.

**Comment by HolgerEssler** [comment]
@paregorios do you think this can be merged and we can close the corresponding issues?

**Comment by paregorios** [comment]
@HolgerEssler sorry for the delay; I'll undertake to do this shortly

**Comment by paregorios** [comment]
merging as requested

**Pull request merged**
